version: "3.8"
services:
  server:
    build:
      context: .
      target: server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=localhost
    env_file: .env
    networks:
      - network
  app:
    build:
      context: .
      target: app
    ports:
      - "3005:3005"
    environment:
      - VITE_API_URL=http://localhost:3000/graphql
      - VITE_WEBSOCKET_API_URL=ws://localhost:3000/graphql
      - PORT=3005
    networks:
      - network
    depends_on:
      - server

networks:
  network:
